name: Invoke Reusable PR Test

on:
  pull_request:
    branches:
      - develop
      - 'v[0-9]+.[0-9]+'

jobs:
  PR:
    uses: Civdrone/actions/.github/workflows/reusable_PR_workflow.yaml@develop
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}